//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations.Schema;
using Location.IModel;

namespace Location.Model.LocationTables
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.Serialization;
    using Work;

    [DataContract]
    public partial class DevInfo: INode
    {
        [DataMember]
        public int? Id { get; set; }

        /// <summary>
        /// 设备Id
        /// </summary>
        [DataMember]
        [Key]
        public string DevID { get; set; }

        /// <summary>
        /// KKS码（设备标识码）
        /// </summary>
        [Display(Name = "KKS码")]
        [DataMember]
        public string KKSCode { get; set; }

        [DataMember]
        public int TypeCode { get; set; }

        private string _typeName = "";

        [NotMapped]//暂时不需要相应的数据库映射
        [DataMember]
        public string TypeName
        {
            get
            {
                if (TypeCode == 20180821)
                {
                    return "摄像头";
                }
                else
                {
                    return "生产设备";
                }
                return _typeName;
                //todo:这里改成设备类型表中获取的设备类型信息
            }
            set
            {
                _typeName = value;
            }
        }

        /// <summary>
        /// 父设备Id，如机柜设备对应的机柜
        /// </summary>
        [DataMember]
        public string PDevID { get; set; }
        [DataMember]
        public string Name { get; set; }
        /// <summary>
        /// 模型名称，用于加载AssetBundle
        /// </summary>
        [Display(Name = "模型名称")]
        [DataMember]
        public string ModelName { get; set; }

        [DataMember]
        public int Status { get; set; }
        [DataMember]
        public System.DateTime CreateTime { get; set; }
        [DataMember]
        public System.DateTime ModifyTime { get; set; }
        [DataMember]
        public string UserName { get; set; }
        [DataMember]
        public string IP { get; set; }

        /// <summary>
        /// 区域Id
        /// </summary>
        [DataMember]
        public int? ParentId { get; set; }

        /// <summary>
        /// 所在区域/机房
        /// </summary>
        [DataMember]
        public virtual PhysicalTopology Parent { get; set; }

        [NotMapped]
        [DataMember]
        public string Path { get; set; }

        [DataMember]
        public string PosId { get; set; }

        [DataMember]
        public virtual DevPos Pos { get; set; }

        public DevInfo()
        {
            CreateTime = DateTime.Now;
            ModifyTime= DateTime.Now;
        }
    }
}
