// <auto-generated />
namespace DAL.LocationDbMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _0115 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_0115));
        
        string IMigrationMetadata.Id
        {
            get { return "201907050703374_0115"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
