//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Location.TModel.Tools;

namespace DbModel.Location.AreaAndDev
{
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.Serialization;
    using Tools;

    /// <summary>
    /// 设备模型
    /// </summary>
    [DataContract]
    public partial class DevModel
    {
        /// <summary>
        /// 主键Id
        /// </summary>
        [DataMember]
        [Display(Name = "主键Id")]
        public int Id { get; set; }

        /// <summary>
        /// 名称
        /// </summary>
        [DataMember]
        [Display(Name = "名称")]
        [MaxLength(128)]
        public string Name { get; set; }

        /// <summary>
        /// 模型Id
        /// </summary>
        [DataMember]
        [Display(Name = "模型Id")]
        [MaxLength(128)]
        public string ModelId { get; set; }

        /// <summary>
        /// 大项
        /// </summary>
        [DataMember]
        [Display(Name = "大项")]
        [MaxLength(16)]
        public string Items { get; set; }

        /// <summary>
        /// 大类
        /// </summary>
        [DataMember]
        [Display(Name = "大类")]
        [MaxLength(32)]
        public string Class { get; set; }

        public DevModel Clone()
        {
            var copy = this.CloneObjectByBinary();
            return copy;
        }
        
    }
}
