//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServiceForWPF.LocationCallbackServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LocationCallbackServices.ILocationAlarmService")]
    public interface ILocationAlarmService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocationAlarmService/Connect", ReplyAction="http://tempuri.org/ILocationAlarmService/ConnectResponse")]
        void Connect();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocationAlarmService/DisConnect", ReplyAction="http://tempuri.org/ILocationAlarmService/DisConnectResponse")]
        void DisConnect();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocationAlarmService/AddAlarmInfo", ReplyAction="http://tempuri.org/ILocationAlarmService/AddAlarmInfoResponse")]
        void AddAlarmInfo(string AlarmInfo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILocationAlarmServiceChannel : WCFServiceForWPF.LocationCallbackServices.ILocationAlarmService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LocationAlarmServiceClient : System.ServiceModel.ClientBase<WCFServiceForWPF.LocationCallbackServices.ILocationAlarmService>, WCFServiceForWPF.LocationCallbackServices.ILocationAlarmService {
        
        public LocationAlarmServiceClient() {
        }
        
        public LocationAlarmServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LocationAlarmServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LocationAlarmServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LocationAlarmServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Connect() {
            base.Channel.Connect();
        }
        
        public void DisConnect() {
            base.Channel.DisConnect();
        }
        
        public void AddAlarmInfo(string AlarmInfo) {
            base.Channel.AddAlarmInfo(AlarmInfo);
        }
    }
}
